// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQcxoRpyVtVLuboUIU0aifQaQ13T0Oks',
    appId: '1:112529270082:web:8440196db3b53d7aa014db',
    messagingSenderId: '112529270082',
    projectId: 'notification-app-d1909',
    authDomain: 'notification-app-d1909.firebaseapp.com',
    storageBucket: 'notification-app-d1909.appspot.com',
    measurementId: 'G-KMFYPK48BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAtQOvF7x_1Wt_Wb_RNITVNOyfOfornk',
    appId: '1:112529270082:android:123e3acb053e1cf9a014db',
    messagingSenderId: '112529270082',
    projectId: 'notification-app-d1909',
    storageBucket: 'notification-app-d1909.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQcxoRpyVtVLuboUIU0aifQaQ13T0Oks',
    appId: '1:112529270082:web:86549d5c0daef2fca014db',
    messagingSenderId: '112529270082',
    projectId: 'notification-app-d1909',
    authDomain: 'notification-app-d1909.firebaseapp.com',
    storageBucket: 'notification-app-d1909.appspot.com',
    measurementId: 'G-GXEKHEH7HW',
  );
}
